# Generated by Django 2.2 on 2020-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is the default description about the product'),
            preserve_default=False,
        ),
    ]
